version: '3.7'
services:

  redis:
    image: redis:latest
    command:
      - redis-server
    env_file: .env
    volumes:
      - 'redisdata:/data'
    restart: on-failure
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    restart: on-failure
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT"
  
  bot:
    build: .
    command: sh -c "python telegram_bot/bot.py"
    env_file: .env
    restart: always
    depends_on:
      - db
      - redis



volumes:
  pgdata:
  redisdata: